#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
#  JOUST – Generate .env.local for the Next.js frontend
#  Usage:  ./generate-env.sh            (auto-detect LAN IP)
#          ./generate-env.sh --clean    (full reset)
#          ./generate-env.sh 10.0.0.42  (manual override)
# ─────────────────────────────────────────────────────────
set -euo pipefail

# ── Setup & Cleanup ──────────────────────────────────────
CLEAN_MODE=false
HOST_OVERRIDE=""

for arg in "$@"; do
  if [[ "$arg" == "--clean" ]]; then
    CLEAN_MODE=true
  elif [[ "$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || [[ "$arg" == "localhost" ]]; then
    HOST_OVERRIDE="$arg"
  fi
done

echo ""
echo "[1/1] 🌐 Generating environment configuration..."

# ── Environment Generation ────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.local"

BACKEND_PORT="${BACKEND_PORT:-4000}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"

# ── Detect LAN IP ────────────────────────────────────────
if [[ -n "$HOST_OVERRIDE" ]]; then
  HOST_IP="$HOST_OVERRIDE"
  echo "Using host: $HOST_IP"
else
  # Try ip route first (Linux), fall back to ifconfig (macOS)
  if command -v ip &>/dev/null; then
    HOST_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)"
  fi

  if [[ -z "${HOST_IP:-}" ]] && command -v ifconfig &>/dev/null; then
    HOST_IP="$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | head -1 | awk '{print $2}')"
  fi

  if [[ -z "${HOST_IP:-}" ]]; then
    HOST_IP="localhost"
    echo "⚠  Could not detect LAN IP — defaulting to localhost"
  else
    echo "Detected LAN IP: $HOST_IP"
  fi
fi

# ── Write .env.local ─────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by generate-env.sh — $(date '+%Y-%m-%d %H:%M:%S')
# Re-run the script any time your network changes.

HOST_IP=$HOST_IP
BACKEND_PORT=$BACKEND_PORT
NEXT_PUBLIC_API_URL=http://$HOST_IP:$BACKEND_PORT
EOF

echo ""
echo "✅ Setup complete! Wrote $ENV_FILE"
echo "   NEXT_PUBLIC_API_URL=http://$HOST_IP:$BACKEND_PORT"
echo ""
echo "Run 'npm run dev' to start the frontend."
echo ""
