@echo off
REM ─────────────────────────────────────────────────────────
REM  JOUST – Generate .env.local for the Next.js frontend
REM  Usage:  generate-env.bat            (auto-detect LAN IP)
REM          generate-env.bat --clean    (full reset)
REM          generate-env.bat 10.0.0.42  (manual override)
REM ─────────────────────────────────────────────────────────
setlocal enabledelayedexpansion

set "CLEAN_MODE=false"
set "HOST_OVERRIDE="

for %%a in (%*) do (
    if "%%a"=="--clean" (
        set "CLEAN_MODE=true"
    ) else (
        set "HOST_OVERRIDE=%%a"
    )
)

echo.
echo [1/1] ^|^| Generating environment configuration...

REM ── Environment Generation ────────────────────────────────
set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%.env.local"

if not defined BACKEND_PORT set "BACKEND_PORT=4000"
if not defined FRONTEND_PORT set "FRONTEND_PORT=3000"

REM ── Detect LAN IP ──────────────────────────────────────
if not "!HOST_OVERRIDE!"=="" (
    set "HOST_IP=!HOST_OVERRIDE!"
    echo Using host: !HOST_IP!
    goto write_env
)

REM Use PowerShell to reliably grab the LAN IPv4 address
for /f "usebackq tokens=*" %%A in (`powershell -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch 'Loopback' -and $_.IPAddress -notmatch '^169\.' -and $_.IPAddress -ne '127.0.0.1' } | Select-Object -First 1).IPAddress"`) do (
    set "HOST_IP=%%A"
)

if not defined HOST_IP (
    echo [WARNING] Could not detect LAN IP -- defaulting to localhost
    set "HOST_IP=localhost"
) else (
    echo Detected LAN IP: !HOST_IP!
)

:write_env
REM ── Write .env.local ───────────────────────────────────
(
    echo # Auto-generated by generate-env.bat -- %date% %time%
    echo # Re-run the script any time your network changes.
    echo.
    echo HOST_IP=!HOST_IP!
    echo BACKEND_PORT=!BACKEND_PORT!
    echo NEXT_PUBLIC_API_URL=http://!HOST_IP!:!BACKEND_PORT!
) > "%ENV_FILE%"

echo.
echo [OK] Setup complete! Wrote %ENV_FILE%
echo    NEXT_PUBLIC_API_URL=http://!HOST_IP!:!BACKEND_PORT!
echo.
echo Start the dev server with:  npm run dev
echo.

endlocal
