const { execSync } = require('child_process');
const os = require('os');
const fs = require('fs');
const path = require('path');

/**
 * JOUST - Setup Dispatcher (Networking focus)
 * This script handles LAN IP detection and .env.local generation
 * for both Windows and Linux/macOS.
 */

const args = process.argv.slice(2);
let hostOverride = '';

// Simple arg parsing
for (const arg of args) {
  if (arg === '--clean') {
    // Legacy flag, ignored for now as per instructions
    continue;
  }
  if (/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/.test(arg) || arg === 'localhost') {
    hostOverride = arg;
  }
}

console.log('\x1b[36m%s\x1b[0m', '─────────────────────────────────────────────────────────');
console.log('\x1b[36m%s\x1b[0m', '  JOUST – Professional Setup & Networking Initialization');
console.log('\x1b[36m%s\x1b[0m', '─────────────────────────────────────────────────────────');

function getLocalIP() {
  if (hostOverride) {
    console.log(`Using host override: ${hostOverride}`);
    return hostOverride;
  }

  // Strategy 1: Linux/macOS 'ip route' or 'ifconfig'
  if (os.platform() !== 'win32') {
    try {
      // Find the interface that routes to 1.1.1.1 (most reliable for LAN IP)
      const ipRoute = execSync("ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i==\"src\") print $(i+1)}' | head -1", { encoding: 'utf8' }).trim();
      if (ipRoute) return ipRoute;
    } catch (e) {
      try {
        const ifconfig = execSync("ifconfig | grep 'inet ' | grep -v '127.0.0.1' | head -1 | awk '{print $2}'", { encoding: 'utf8' }).trim();
        if (ifconfig) return ifconfig;
      } catch (e2) {}
    }
  }

  // Strategy 2: Node.js os.networkInterfaces (Cross-platform)
  const nets = os.networkInterfaces();
  const results = [];

  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      // Skip internal and non-IPv4
      if (net.family === 'IPv4' && !net.internal) {
        // Skip APIPA
        if (!net.address.startsWith('169.254.')) {
          results.push(net.address);
        }
      }
    }
  }

  if (results.length > 0) {
    // Prefer 192.168.x.x or 10.x.x.x addresses if multiple exist
    const preferred = results.find(ip => ip.startsWith('192.168.') || ip.startsWith('10.'));
    return preferred || results[0];
  }

  return 'localhost';
}

try {
  const hostIP = getLocalIP();
  const backendPort = process.env.BACKEND_PORT || '4000';
  const envFile = path.join(__dirname, '.env.local');

  console.log(`Detected LAN IP: ${hostIP}`);

  const envContent = `# Auto-generated by setup.js — ${new Date().toISOString().replace('T', ' ').split('.')[0]}
# Re-run the script any time your network changes.

HOST_IP=${hostIP}
BACKEND_PORT=${backendPort}
NEXT_PUBLIC_API_URL=http://${hostIP}:${backendPort}
`;

  fs.writeFileSync(envFile, envContent);

  console.log('\x1b[32m%s\x1b[0m', `✅ Setup complete! Wrote ${envFile}`);
  console.log(`   NEXT_PUBLIC_API_URL=http://${hostIP}:${backendPort}`);
  console.log('');
  console.log('Run \x1b[33mnpm run dev\x1b[0m to start the frontend.');
  console.log('');

} catch (error) {
  console.error('\x1b[31m%s\x1b[0m', '❌ Setup failed:');
  console.error(error.message);
  process.exit(1);
}
